{% set name = "WaLSAtools" %}
{% set version = "1.0.0.post1" %}
{% set sha256 = "6b61a32a37b629fba3f0ba631715119eb565a6188016b82e113925074ac2354f" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - astropy ==7.0.1
    - ipython ==8.32.0
    - ipywidgets ==8.1.5
    - matplotlib ==3.10.0
    - numba ==0.61.0
    - numpy ==2.1.3
    - pyFFTW ==0.15.0
    - scipy ==1.15.1
    - setuptools ==75.8.0
    - scikit-image ==0.25.1
    - tqdm ==4.67.1

test:
  imports:
    - WaLSAtools

about:
  home: "https://github.com/WaLSAteam/WaLSAtools"
  summary: "Wave analysis tools package for spectral and spatio-temporal analysis"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
